src/main/java/de/p23r/client/portal/marm/RuleBean.java
package de.p23r.client.portal.marm;

import java.io.Serializable;
import java.util.List;

import javax.xml.datatype.XMLGregorianCalendar;

import de.p23r.common.modelandrulemanagement.archive.NotificationRulePackageArchive;
import de.p23r.leitstelle.ns.p23r.iruleactivate1_0.types.RuleStateType;
import de.p23r.leitstelle.ns.p23r.nrl.commonnrl1_1.Description;
import de.p23r.leitstelle.ns.p23r.nrl.rulemanifest1_1.RuleManifest;

/**
 * The Class RuleBean.
 */
public class RuleBean implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 656373669545473852L;

    private RuleStateType state;
    private NotificationRulePackageArchive archive;
    private RuleManifest manifest;
    private String path;

    /**
     * Instantiates a new rule bean.
     *
     * @param state the state
     * @param archive the archive
     * @param groupPath the group path
     */
    public RuleBean(RuleStateType state, NotificationRulePackageArchive archive, String groupPath) {
        this.state = state;
        this.archive = archive;

        List<String> rulePaths = this.archive.getNotificationRulePathes(groupPath);
        for (String rulePath : rulePaths) {
            RuleManifest ruleManifest = this.archive.getNotificationRuleManifestHelper(rulePath);
            if (state.getId().equals(ruleManifest.getId())) {
                manifest = ruleManifest;
                path = rulePath;
            }
        }
    }

    /**
     * Sets the state.
     *
     * @param state the new state
     */
    public void setState(RuleStateType state) {
        this.state = state;
    }

    /**
     * Gets the id.
     *
     * @return the id
     */
    public String getId() {
        return manifest.getId();
    }

    /**
     * Gets the name.
     *
     * @return the name
     */
    public String getName() {
        return manifest.getName();
    }

    /**
     * Gets the release.
     *
     * @return the release
     */
    public String getRelease() {
        return manifest.getRelease();
    }

    /**
     * Gets the title.
     *
     * @return the title
     */
    public String getTitle() {
        return manifest.getTitle();
    }

    /**
     * Checks if is active.
     *
     * @return true, if is active
     */
    public boolean isActive() {
        return state.isIsActive();
    }

    /**
     * Checks if is deactivated.
     *
     * @return true, if is deactivated
     */
    public boolean isDeactivated() {
        return state.isIsDeactivated();
    }

    /**
     * Gets the descriptions.
     *
     * @return the descriptions
     */
    public List<Description> getDescriptions() {
        return manifest.getDescriptions();
    }

    /**
     * Gets the hints.
     *
     * @return the hints
     */
    public List<Description> getHints() {
        return manifest.getHints();
    }

    /**
     * Gets the targets.
     *
     * @return the targets
     */
    public List<Description> getTargets() {
        return manifest.getTargets();
    }

    /**
     * Gets the legal backgrounds.
     *
     * @return the legal backgrounds
     */
    public List<Description> getLegalBackgrounds() {
        return manifest.getLegalBackgrounds();
    }

    /**
     * Gets the creators.
     *
     * @return the creators
     */
    public List<String> getCreators() {
        return manifest.getCreators();
    }

    /**
     * Gets the subjects.
     *
     * @return the subjects
     */
    public List<String> getSubjects() {
        return manifest.getSubjects();
    }

    /**
     * Gets the warnings.
     *
     * @return the warnings
     */
    public List<String> getWarnings() {
        return state.getWarnings();
    }

    /**
     * Gets the errors.
     *
     * @return the errors
     */
    public List<String> getErrors() {
        return state.getErrors();
    }

    /**
     * Gets the submit at daily periods.
     *
     * @return the submit at daily periods
     */
    public List<XMLGregorianCalendar> getSubmitAtDailyPeriods() {
        return manifest.getSubmitAtDailyPeriods();
    }

    /**
     * Gets the submit at weekly periods.
     *
     * @return the submit at weekly periods
     */
    public List<Integer> getSubmitAtWeeklyPeriods() {
        return manifest.getSubmitAtWeeklyPeriods();
    }

    /**
     * Gets the submit at monthly periods.
     *
     * @return the submit at monthly periods
     */
    public List<XMLGregorianCalendar> getSubmitAtMonthlyPeriods() {
        return manifest.getSubmitAtMonthlyPeriods();
    }

    /**
     * Gets the submit at yearly periods.
     *
     * @return the submit at yearly periods
     */
    public List<XMLGregorianCalendar> getSubmitAtYearlyPeriods() {
        return manifest.getSubmitAtYearlyPeriods();
    }

    /**
     * Gets the submit ats.
     *
     * @return the submit ats
     */
    public List<XMLGregorianCalendar> getSubmitAts() {
        return manifest.getSubmitAts();
    }

    /**
     * Gets the message schema.
     *
     * @return the message schema
     */
    public String getMessageSchema() {
        return archive.getNotificationRuleMessageSchema(path);
    }

    /**
     * Gets the valid from.
     *
     * @return the valid from
     */
    public XMLGregorianCalendar getValidFrom() {
        return manifest.getValidFrom();
    }

    /**
     * Gets the valid until.
     *
     * @return the valid until
     */
    public XMLGregorianCalendar getValidUntil() {
        return manifest.getValidUntil();
    }

}

src/main/java/de/p23r/client/portal/marm/RulePackageBean.java
package de.p23r.client.portal.marm;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import de.p23r.common.modelandrulemanagement.archive.NotificationRulePackageArchive;
import de.p23r.leitstelle.ns.p23r.iruleactivate1_0.types.RuleGroupStateType;
import de.p23r.leitstelle.ns.p23r.iruleactivate1_0.types.RulePackageStateType;
import de.p23r.leitstelle.ns.p23r.nrl.commonnrl1_1.Description;
import de.p23r.leitstelle.ns.p23r.nrl.rulepackagemanifest1_1.RulePackageManifest;

/**
 * The Class RulePackageBean.
 */
public class RulePackageBean implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = -2042483246498558164L;

    private RulePackageStateType state;
    private NotificationRulePackageArchive archive;
    private RulePackageManifest manifest;

    /**
     * Instantiates a new rule package bean.
     *
     * @param state the state
     * @param archive the archive
     */
    public RulePackageBean(RulePackageStateType state, NotificationRulePackageArchive archive) {
        this.state = state;
        this.archive = archive;
        manifest = this.archive.getNotificationRulePackageManifestHelper();
    }

    /**
     * Sets the state.
     *
     * @param state the new state
     */
    public void setState(RulePackageStateType state) {
        this.state = state;
    }

    /**
     * Checks if is supported.
     *
     * @return true, if is supported
     */
    public boolean isSupported() {
        return state.isIsSupported();
    }

    /**
     * Checks if is selected.
     *
     * @return true, if is selected
     */
    public boolean isSelected() {
        return state.isIsSelected();
    }

    /**
     * Checks if is recommended.
     *
     * @return true, if is recommended
     */
    public boolean isRecommended() {
        return state.isIsRecommended();
    }

    /**
     * Gets the id.
     *
     * @return the id
     */
    public String getId() {
        return manifest.getId();
    }

    /**
     * Gets the name.
     *
     * @return the name
     */
    public String getName() {
        return manifest.getName();
    }

    /**
     * Gets the release.
     *
     * @return the release
     */
    public String getRelease() {
        return manifest.getRelease();
    }

    /**
     * Gets the title.
     *
     * @return the title
     */
    public String getTitle() {
        return manifest.getTitle();
    }

    /**
     * Gets the descriptions.
     *
     * @return the descriptions
     */
    public List<Description> getDescriptions() {
        return manifest.getDescriptions();
    }

    /**
     * Gets the hints.
     *
     * @return the hints
     */
    public List<Description> getHints() {
        return manifest.getHints();
    }

    /**
     * Gets the targets.
     *
     * @return the targets
     */
    public List<Description> getTargets() {
        return manifest.getTargets();
    }

    /**
     * Gets the licenses.
     *
     * @return the licenses
     */
    public List<Description> getLicenses() {
        return manifest.getLicenses();
    }

    /**
     * Gets the publisher.
     *
     * @return the publisher
     */
    public String getPublisher() {
        return manifest.getPublisher();
    }

    /**
     * Gets the creators.
     *
     * @return the creators
     */
    public List<String> getCreators() {
        return manifest.getCreators();
    }

    /**
     * Gets the subjects.
     *
     * @return the subjects
     */
    public List<String> getSubjects() {
        return manifest.getSubjects();
    }

    /**
     * Gets the warnings.
     *
     * @return the warnings
     */
    public List<String> getWarnings() {
        return state.getWarnings();
    }

    /**
     * Gets the errors.
     *
     * @return the errors
     */
    public List<String> getErrors() {
        return state.getErrors();
    }

    /**
     * Gets the rule groups.
     *
     * @return the rule groups
     */
    public List<RuleGroupBean> getRuleGroups() {
        List<RuleGroupBean> groups = new ArrayList<RuleGroupBean>();
        for (RuleGroupStateType groupState : state.getRuleGroups()) {
            groups.add(new RuleGroupBean(groupState, archive));
        }
        return groups;
    }

}

src/main/java/de/p23r/client/portal/protocolpool/ProtocolEntryBean.java
package de.p23r.client.portal.protocolpool;

import java.io.Serializable;
import java.util.List;
import java.util.Locale;

import de.p23r.leitstelle.ns.p23r.commonprotocol1_0.ProtocolEntry;
import de.p23r.leitstelle.ns.p23r.nrl.commonnrl1_1.Description;

/**
 * The Class ProtocolEntryBean.
 */
public class ProtocolEntryBean implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 5539331379450548191L;

    private ProtocolEntry entry;

    /**
     * Gets the entry.
     *
     * @return the entry
     */
    public ProtocolEntry getEntry() {
        return entry;
    }

    /**
     * Sets the entry.
     *
     * @param entry the new entry
     */
    public void setEntry(ProtocolEntry entry) {
        this.entry = entry;
    }

    /**
     * Checks for details.
     *
     * @return true, if successful
     */
    public boolean hasDetails() {
        if (entry.getMessageId() != null || entry.getNotificationId() != null || entry.getRuleId() != null) {
            return true;
        }
        if (entry.getRuleName() != null || entry.getTransactionId() != null || hasTrace()) {
            return true;
        }
        return false;
    }

    /**
     * Gets the image name.
     *
     * @return the image name
     */
    public String getImageName() {
        String image = null;
        if (entry.getContent().getLog() != null) {
            switch (entry.getContent().getLog().getLevel()) {
            case ERROR:
                image = "exclamation-icon.png";
                break;
            case WARNING:
                image = "warning.png";
                break;
            case TEST_SUCCESS:
                image = "success.png";
                break;
            case TEST_FAIL:
                image = "failure.png";
                break;
            case SECURITY:
                image = "security.png";
                break;
            case FATAL:
                image = "fatal.png";
                break;
            case INFO:
            default:
                image = "info.png";
                break;
            }
        } else if (entry.getContent().getTrace() != null) {
            image = "trace.png";
        } else {
            image = "questionmark.png";
        }
        return image;
    }

    /**
     * Checks for log.
     *
     * @return true, if successful
     */
    public boolean hasLog() {
        return entry.getContent().getLog() != null;
    }

    /**
     * Checks for trace.
     *
     * @return true, if successful
     */
    public boolean hasTrace() {
        return entry.getContent().getTrace() != null;
    }

    /**
     * Checks for generic content.
     *
     * @return true, if successful
     */
    public boolean hasGenericContent() {
        return entry.getContent().getGenericContent() != null;
    }
    
    /**
     * Gets the log content.
     *
     * @return the log content
     */
    public String getLogContent() {
        List<Description> descriptions = entry.getContent().getLog().getNotes();
        return getDescription(descriptions, Locale.getDefault());        
    }
    
    /**
     * Gets the trace content.
     *
     * @return the trace content
     */
    public String getTraceContent() {
        List<Description> descriptions = entry.getContent().getTrace().getNotes();
        return getDescription(descriptions, Locale.getDefault());        
    }
    
    /**
     * Return the description content for the given language if available or any or null if not.
     * @param descriptions
     * @param locale
     * @return content
     */
    private String getDescription(List<Description> descriptions, Locale locale) {
        for (Description desc : descriptions) {
            if (locale.getLanguage().equals(new Locale(desc.getLang()).getLanguage())) {
                return desc.getContent();
            }
        }
        //TODO return or return not any available content if there is no one for the current language?
        if (!descriptions.isEmpty()) {
            return descriptions.get(0).getContent();
        }
        return null;
    }
}

src/main/java/de/p23r/client/portal/session/LoginAction.java
package de.p23r.client.portal.session;

import java.io.IOException;
import java.io.Serializable;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.picketlink.Identity;
import org.picketlink.Identity.AuthenticationResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * The Class LoginAction.
 */
@Named
@RequestScoped
public class LoginAction implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 7332232621290392397L;

    private static final transient Logger LOG = LoggerFactory.getLogger(LoginAction.class);

    @Inject
    private Identity identity;

    private String from;

    /**
     * Login.
     */
    public void login() {
        if (AuthenticationResult.SUCCESS.equals(identity.login())) {
            try {
                FacesContext.getCurrentInstance().getExternalContext().redirect(from);
            } catch (IOException e) {
                LOG.error("Login failed.", e);
            }
        }
    }

    /**
     * Gets the from.
     *
     * @return the from
     */
    public String getFrom() {
        return from;
    }

    /**
     * Sets the from.
     *
     * @param from the new from
     */
    public void setFrom(String from) {
        this.from = from;
    }

}

src/main/webapp/secured/error.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      template="../layout/p23rtemplate.xhtml">

    <ui:param name="index" value="0" />

    <ui:define name="body">

        <h2>Anmelden</h2>
    
        <h:form>
            <p:messages id="errorMessage" autoUpdate="true" />

            Authentifizierung schlug fehl!
        </h:form>
    
     </ui:define>

</ui:composition>

src/main/webapp/secured/home.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui" 
    template="../layout/p23rtemplate.xhtml">

    <ui:param name="index" value="0" />

    <ui:define name="body">
        
        <h1>Übersicht</h1>
        
        <h2>Offene Benachrichtigungen</h2>
        <h:form>
            <p:dataTable paginator="true" rows="10" dynamic="true" var="nl" value="#{notificationManager.newReports}" emptyMessage="Keine Benachrichtigungen offen.">
                <p:column>
                    <h:outputText value="#{nl.entryDate}" converter="calendarConverter" />
                </p:column>
                <p:column>
                    <h:outputText value="#{ruleManager.getRuleName(nl.notificationRuleId)}" />
                </p:column>
                <p:column>
                    <p:commandButton id="approve" value="Bearbeiten" action="#{notificationAction.viewNotification(nl)}" />
                </p:column>
            </p:dataTable>
        </h:form>
            
    </ui:define>
    
</ui:composition>

src/main/webapp/secured/login.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      template="../layout/p23rtemplate.xhtml">

    <ui:param name="index" value="0" />

    <ui:define name="body">

        <h:form id="loginform" onsubmit="document.getElementById('loginform').action='j_security_check';" prependId="false">
            <p:messages id="errorMessage" autoUpdate="true" />
            <p:panelGrid columns="1" rendered="#{!identity.loggedIn}">
                <p:inputText id="j_username" name="j_username" value="#{loginCredentials.userId}" placeholder="Benutzername" />
                <p:password id="j_password" name="j_password" value="#{loginCredentials.password}" placeholder="Passwort" />
                <p:commandButton id="submit" value="Anmelden" immediate="true" ajax="false"/>
            </p:panelGrid>
            <h:panelGroup rendered="#{identity.loggedIn}">
                <h:outputText value="Hallo #{identity.account.loginName}, du bist bereits angemeldet." />
                <br />
                <br />
                <p:commandButton id="logout" value="Logout" action="#{identity.logout}" />
            </h:panelGroup>            
        </h:form>
    
     </ui:define>

</ui:composition>

src/main/webapp/secured/packagerule.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:pe="http://primefaces.org/ui/extensions"
    xmlns:p="http://primefaces.org/ui"
    template="../layout/p23rtemplate.xhtml">

    <ui:param name="index" value="1" />

    <ui:define name="breadcrumb">
        <h:form id="breadCrumbForm">
            <p:breadCrumb>
                <p:menuitem value="home" url="/secured/packagelist.xhtml" />
                <p:menuitem value="#{rulePackageManager.rulePackage.name}" url="/secured/package.xhtml" />
                <p:menuitem value="#{ruleGroupManager.ruleGroup.name}" url="/secured/packagegroup.xhtml" />
                <p:menuitem value="#{ruleManager.rule.name}" url="#" />
            </p:breadCrumb>
        </h:form>
    </ui:define>

    <ui:define name="body">

    <p:ajaxStatus onstart="statusDialog.show();" onsuccess="statusDialog.hide();"/>  
              
    <p:dialog modal="true" widgetVar="statusDialog" draggable="false" closable="false" showHeader="false" resizable="false">  
        <p:graphicImage library="images" name="ajax-loader.gif" />
    </p:dialog>  
    
    <h1><h:outputText value="#{ruleManager.rule.title}" /></h1>

    <h:form id="ruleForm">    

        <p:dialog header="Nachricht" resizable="false" modal="true" widgetVar="messageDialog" dynamic="true" width="600" >
            <pe:codeMirror mode="xml" value="#{ruleGenerateAction.message}" lineWrapping="true" readOnly="false" />
            <p/>
            <p:commandButton id="send" value="Versenden" action="#{ruleGenerateAction.send}" onclick="messageDialog.hide()"/>
        </p:dialog>
    
        <p:messages id="p23rmessages" autoUpdate="true" closable="true" />  
            
        <p:fieldset>
            <h:panelGroup id="status" style="float: right;">
                <p:graphicImage library="images" name="#{ruleManager.rule.deactivated ? 'lightbulb_off.png' : 'lightbulb.png'}" style="vertical-align: bottom;"/>
                <h:outputText value="#{ruleManager.rule.deactivated ? ' Deaktiviert' : ' Aktiviert'}" />
                <p:spacer width="20" />
                <p:graphicImage library="images" name="#{ruleManager.rule.active ? 'clock.png' : 'clock_red.png'}" style="vertical-align: bottom;"/>    
                <h:outputText value="#{ruleManager.rule.active ? ' Zur Zeit aktiv' : ' Zur Zeit nicht aktiv'}" />
                <p:spacer width="10" />
            </h:panelGroup>

            <p:commandButton id="generate" global="false" value="Auslösen" action="#{ruleGenerateAction.editMessage(ruleManager.rule)}" oncomplete="messageDialog.show()" title="Bietet die Möglichkeit die Regel manuell auszulösen" styleClass="ui-priority-primary" disabled="#{ruleManager.rule.deactivated}" />
            <p:spacer width="10" />
            <p:commandButton id="deactivation" value="Deaktivieren" action="#{ruleManager.deactivateRule()}" update="ruleForm" disabled="#{ruleManager.rule.deactivated}" />
            <p:spacer width="20" />
            <h:outputText value="Freigabe" />
            <p:spacer width="5" />
            <p:selectOneButton style="display:inline-block;" value="#{ruleManager.autoApproval}" valueChangeListener="#{ruleManager.toggleAutoApproval}" disabled="#{ruleManager.rule.deactivated}">
                <f:selectItem itemLabel="manuell" itemValue="false" />
                <f:selectItem itemLabel="automatisch" itemValue="true" />
            </p:selectOneButton>
            
            <div style="clear:both;" />
            <p/>
            <h:outputText value="#{ruleManager.rule.descriptions}" converter="languageSelectionConverter" />
            <p/>
            <h:outputText value="#{ruleManager.rule.targets}" converter="languageSelectionConverter" />        
            <p/>
            <h:panelGroup rendered="#{not empty ruleManager.rule.hints}">
                <h:outputText value="Hinweis: " />
                <h:outputText value="#{ruleManager.rule.hints}" converter="languageSelectionConverter" />            
            </h:panelGroup>
            <p/>
            <h:panelGroup rendered="#{not empty ruleManager.rule.creators}">
                <h:outputText value="Erstellt von " />
                <h:outputText value="#{ruleManager.rule.creators}" converter="listStringConverter" />
            </h:panelGroup>
            <p/>

            <h:panelGroup rendered="#{not empty ruleManager.rule.legalBackgrounds}">
                <h:outputText value="Rechtliche Hintergründe: " />
                <h:outputText value="#{ruleManager.rule.legalBackgrounds}" converter="languageSelectionConverter" />
            </h:panelGroup>    

        </p:fieldset>
        <p />

        <p:panel toggleable="true" collapsed="true">
            <f:facet name="header">
                <p:graphicImage library="images" name="#{ruleManager.rule.active ? 'clock.png' : 'clock_red.png'}" style="vertical-align: bottom;"/>    
                <p:spacer width="10" />
                <h:outputText value="Ausführungen zwischen #{ruleManager.rule.validFrom} und #{ruleManager.rule.validUntil} (Gültigkeitszeitraum)" />            
            </f:facet>
            <pe:timeline id="timeline" value="#{ruleManager.model}" showCurrentTime="true" zoomable="true" stackEvents="true" selectable="false" showNavigation="true" />
        </p:panel>                
        <p />
        <h:panelGroup id="warnings" rendered="#{not empty ruleManager.rule.warnings}" >
            <h:graphicImage library="images" name="exclamation.png" style="vertical-align:top;" />Aufgetretene Warnungen: <h:outputText value="#{ruleManager.rule.warnings}" converter="listStringConverter" />
        </h:panelGroup>
        <p />        
        <h:panelGroup id="errors" rendered="#{not empty ruleManager.rule.errors}">
            <h:graphicImage library="images" name="error.png" style="vertical-align:top;" />Aufgetretene Fehler: <h:outputText value="#{ruleManager.rule.errors}" converter="listStringConverter" />
        </h:panelGroup>
        <p />        
        
    </h:form>

    </ui:define>

</ui:composition>

src/main/webapp/secured/protocol.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    template="../layout/p23rtemplate.xhtml">

    <ui:param name="index" value="3" />

    <ui:define name="body">

        <h1>Protokoll anzeigen</h1>

        <h:form id="protokoll">
            <!-- Filter reset button -->
            <p:commandButton value="Filter zurücksetzen"
                action="#{protocolFilter.reset()}" update="entries" />
            <p />
            
            <!-- Protocol table -->
            <p:dataTable paginator="true" rows="10" lazy="true" id="entries"
                var="pel" value="#{protocolQueryManager.protocolEntries}"
                emptyMessage="Keine Protokolleinträge vorhanden.">

                <!-- Details toggler -->
                <p:column>
                    <p:rowToggler rendered="#{pel.hasDetails()}" />
                </p:column>

                <!-- Image -->
                <p:column>
                    <h:graphicImage library="images" name="#{pel.imageName}" />
                </p:column>
                
                <!-- Component Name -->
                <p:column>
                    <div style="max-width: 80px; font-size: 90%;">
                        <h:outputText rendered="#{pel.hasLog()}" value="#{pel.entry.content.log.componentName}"
                            title="#{pel.entry.content.log.componentName}" />
                        <h:outputText rendered="#{pel.hasTrace()}" value="#{pel.entry.content.trace.step}"
                            title="#{pel.entry.content.trace.step}" />
                    </div>
                </p:column>
                
                <!-- Note -->
                <p:column>
                    <div style="max-width: 450px; font-size: 90%;">
                        <h:outputText rendered="#{pel.hasLog()}"
                            value="#{pel.logContent}"
                            title="#{pel.logContent}" />
                        <h:outputText rendered="#{pel.hasTrace()}"
                            value="#{pel.traceContent}"
                            title="#{pel.traceContent}" />
                        <h:outputText rendered="#{pel.hasGenericContent()}"
                            value="#{pel.entry.content.genericContent}"
                            title="#{pel.entry.content.genericContent}" />
                    </div>
                </p:column>

                <!-- profile and transformation script details link -->
                <p:column>
                    <h:link rendered="#{pel.hasTrace()}" value="Details" outcome="scriptDetails">
                        <f:param name="id" value="#{pel.entry.recordId}" />
                    </h:link>
                </p:column>

                <!-- Date -->
                <p:column style="font-size:90%;">
                    <h:outputText value="#{pel.entry.eventAt}"
                        converter="calendarConverter" />
                </p:column>

                <!-- Details -->
                <p:rowExpansion>
                    <p:panelGrid columns="2" cellspacing="5" rendered="#{pel.hasDetails()}">
                        <h:outputText rendered="#{pel.entry.messageId != null}"
                            value="Nachricht: " />
                        <p:commandLink update="entries"
                            rendered="#{pel.entry.messageId != null}"
                            value="#{pel.entry.messageId}"
                            action="#{protocolFilter.filterMessage(pel.entry.messageId)}" />
                        <h:outputText rendered="#{pel.entry.transactionId != null}"
                            value="Transaktion: " />
                        <p:commandLink update="entries"
                            rendered="#{pel.entry.transactionId != null}"
                            value="#{pel.entry.transactionId}"
                            action="#{protocolFilter.filterTransaction(pel.entry.transactionId)}" />
                        <h:outputText rendered="#{pel.entry.notificationId != null}"
                            value="Benachrichtigung: " />
                        <p:commandLink update="entries"
                            rendered="#{pel.entry.notificationId != null}"
                            value="#{pel.entry.notificationId}"
                            action="#{protocolFilter.filterNotification(pel.entry.notificationId)}" />
                        <h:outputText rendered="#{pel.entry.ruleName != null}"
                            value="Regel: " />
                        <h:outputText rendered="#{pel.entry.ruleName != null}"
                            value="#{pel.entry.ruleName}" />
                        <h:outputText rendered="#{pel.hasTrace()}" value="Step: " />
                        <h:outputText rendered="#{pel.hasTrace()}"
                            value="#{pel.entry.content.trace.step}" />
                    </p:panelGrid>
                </p:rowExpansion>

            </p:dataTable>

        </h:form>

    </ui:define>

</ui:composition>